// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4aN9QpMNzUjC3I9JGJCZGUFCf-8fiR7w',
    appId: '1:209765971846:web:776b617c9b6a54ab391e07',
    messagingSenderId: '209765971846',
    projectId: 'flash-chat-77585',
    authDomain: 'flash-chat-77585.firebaseapp.com',
    storageBucket: 'flash-chat-77585.firebasestorage.app',
    measurementId: 'G-BZ3373D9BN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUyc0z5JMCCyBAyxoB1QUmJj5vH15Jvik',
    appId: '1:209765971846:android:76e9ae93f99683bf391e07',
    messagingSenderId: '209765971846',
    projectId: 'flash-chat-77585',
    storageBucket: 'flash-chat-77585.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBX2I6Ay5c6hXXDEg0QYoY6fCR9BIqBXUc',
    appId: '1:209765971846:ios:dd7e5a727f406355391e07',
    messagingSenderId: '209765971846',
    projectId: 'flash-chat-77585',
    storageBucket: 'flash-chat-77585.firebasestorage.app',
    iosBundleId: 'com.cristianarevalo.flashChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBX2I6Ay5c6hXXDEg0QYoY6fCR9BIqBXUc',
    appId: '1:209765971846:ios:dd7e5a727f406355391e07',
    messagingSenderId: '209765971846',
    projectId: 'flash-chat-77585',
    storageBucket: 'flash-chat-77585.firebasestorage.app',
    iosBundleId: 'com.cristianarevalo.flashChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4aN9QpMNzUjC3I9JGJCZGUFCf-8fiR7w',
    appId: '1:209765971846:web:6da9de00102c2c00391e07',
    messagingSenderId: '209765971846',
    projectId: 'flash-chat-77585',
    authDomain: 'flash-chat-77585.firebaseapp.com',
    storageBucket: 'flash-chat-77585.firebasestorage.app',
    measurementId: 'G-YFRG90PL4W',
  );

}